CREATE TABLE IF NOT EXISTS nsec_tor_exit_nodes (
  ip VARBINARY(16) NOT NULL PRIMARY KEY,
  ip_text VARCHAR(45) NOT NULL,
  source VARCHAR(255) NULL,
  fetched_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
