#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
PH="$ROOT/public_html"
MOD="$PH/modules"
ADD="$ROOT/addons"

ts="$(date -Is)"
out="${2:-$ROOT/storage/memento_report.md}"
mkdir -p "$(dirname "$out")"

echo "# nukeCE Memento Report" > "$out"
echo "" >> "$out"
echo "- Generated: $ts" >> "$out"
echo "- Repo root: $ROOT" >> "$out"
echo "" >> "$out"

section () { echo "" >> "$out"; echo "## $1" >> "$out"; echo "" >> "$out"; }

section "Repo surfaces"
{
  echo "- public_html exists: $(test -d "$PH" && echo yes || echo no)"
  echo "- addons exists: $(test -d "$ADD" && echo yes || echo no)"
  echo "- webroot addons dir (should be denied): $(test -d "$PH/addons" && echo yes || echo no)"
} >> "$out"

section "Modules inventory (public_html/modules)"
if test -d "$MOD"; then
  ls -1 "$MOD" | sort | sed 's/^/- /' >> "$out"
else
  echo "_missing modules dir_" >> "$out"
fi

section "Admin modules"
if test -d "$MOD"; then
  ls -1 "$MOD" | grep '^admin_' | sort | sed 's/^/- /' >> "$out" || true
fi

section "Legacy quarantine"
if test -d "$MOD/_legacy"; then
  find "$MOD/_legacy" -maxdepth 2 -type d | sed "s#^$ROOT/##" | sort | sed 's/^/- /' >> "$out"
else
  echo "_no _legacy directory_" >> "$out"
fi

section "Legacy stubs sanity"
for m in weblinks encyclopedia journal avantgo; do
  if test -d "$MOD/$m"; then
    files="$(find "$MOD/$m" -maxdepth 1 -type f | wc -l | tr -d ' ')"
    echo "- $m: files at top-level = $files" >> "$out"
    if test -f "$MOD/$m/index.php"; then
      head -n 5 "$MOD/$m/index.php" | sed 's/^/  /' >> "$out"
    fi
  fi
done

section "Addons inventory"
if test -d "$ADD"; then
  echo "### addons/modules" >> "$out"
  if test -d "$ADD/modules"; then
    ls -1 "$ADD/modules" | sort | sed 's/^/- /' >> "$out"
  else
    echo "_missing addons/modules_" >> "$out"
  fi
  echo "" >> "$out"
  echo "### addons/optional" >> "$out"
  if test -d "$ADD/optional"; then
    ls -1 "$ADD/optional" | sort | sed 's/^/- /' >> "$out"
  else
    echo "_missing addons/optional_" >> "$out"
  fi
fi

section "Case-conflict detection (Linux-sensitive)"
python3 - <<'PY' "$MOD" >> "$out"
import os, sys
moddir=sys.argv[1]
names=[n for n in os.listdir(moddir) if not n.startswith('.')]
lower={}
conf=[]
for n in names:
  k=n.lower()
  lower.setdefault(k,[]).append(n)
for k,v in sorted(lower.items()):
  if len(v)>1:
    conf.append((k,v))
if not conf:
  print("- none detected")
else:
  for k,v in conf:
    print(f"- {k}: {', '.join(v)}")
PY

section "Router fingerprint"
if test -f "$PH/src/Core/Router.php"; then
  echo "\`\`\`" >> "$out"
  grep -n "resolve" -n "$PH/src/Core/Router.php" | head -n 10 >> "$out" || true
  grep -n "\$_GET\['module'\]" "$PH/src/Core/Router.php" | head -n 5 >> "$out" || true
  echo "\`\`\`" >> "$out"
else
  echo "_Router not found at public_html/src/Core/Router.php_" >> "$out"
fi

echo "" >> "$out"
echo "---" >> "$out"
echo "Generated by tools/inventory_memento.sh" >> "$out"

echo "Wrote: $out"
